


const OrganizationsConfigs = [
    {
        category: 'Student Associations',
        organizations: [
            {
                title: 'NTU Student Association (NTUSA)',
                chinese: '臺大學生會',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/GU6IHJM.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUSA',
                instagram: 'https://www.instagram.com/ntusa_33rd/',
                line: null,
                website: 'https://ntusa.ntu.edu.tw/',
            },
            {
                title: 'NTUSA International Affairs',
                chinese: '臺大學生會國際事務部',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/eHXGa7y.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUSADIA/',
                instagram: 'https://www.instagram.com/ntusadia/',
                line: null,
                website: null,
            },
            {
                title: 'NTUSA Culture',
                chinese: '臺大學生會文化部',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/jarRdnD.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUSACulture',
                instagram: 'https://www.instagram.com/ntuculture/',
                line: null,
                website: null,
            },
            {
                title: 'NTUSA Academics',
                chinese: '臺大學生會學術部',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/JyPUyYb.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUSA.Academics',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTUSA Student Welfare',
                chinese: '臺大學生會學權部',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/H5fkLVw.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUSAstudentwelfare',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTUSA Election Committee',
                chinese: '臺大學生會選委會',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/VThzKVY.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUVote',
                instagram: null,
                line: null,
                website: null,
            },
        ]
    },
    {
        category: 'International Organizations',
        organizations: [
            {
                title: 'NTUSA International Affairs',
                chinese: '臺大學生會國際事務部',
                avatar: 'NTUSA',
                image: 'https://i.imgur.com/eHXGa7y.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUSADIA/',
                instagram: 'https://www.instagram.com/ntusadia/',
                line: null,
                website: null,
            },
            {
                title: 'NTU International Student Information Service (NTU ISIE)',
                chinese: '台大外籍生接待服務社',
                avatar: null,
                image: 'https://i.imgur.com/J7aA4hS.png',
                description: null,
                facebook: 'https://www.facebook.com/NTUISIE',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'ICL Student Association',
                chinese: '國際學伴交流社',
                avatar: null,
                image: 'https://i.imgur.com/md8DZVn.png',
                description: null,
                facebook: 'https://www.facebook.com/ICLStudentAssociation/',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTU Japanese Student Association (NTUJSA)',
                chinese: null,
                avatar: 'Japan',
                image: 'https://i.imgur.com/1aD70YR.png',
                description: null,
                facebook: 'https://www.facebook.com/%E5%9B%BD%E7%AB%8B%E5%8F%B0%E6%B9%BE%E5%A4%A7%E5%AD%A6-%E6%97%A5%E6%9C%AC%E4%BA%BA%E4%BC%9A-414514448656884/',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTU Vietnamese Student Association (NTUVSA)',
                chinese: null,
                avatar: 'Vietnam',
                image: 'https://i.imgur.com/NMpZBGh.png',
                description: null,
                facebook: 'https://www.facebook.com/ntuvsa',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTU Korean Student Association (NTUKSA)',
                chinese: null,
                avatar: 'Korea',
                image: 'https://i.imgur.com/Pm6bsIi.png',
                description: null,
                facebook: 'https://www.facebook.com/%E8%87%BA%E7%81%A3%E5%A4%A7%E5%AD%B8%E9%9F%93%E5%9C%8B%E5%90%8C%E5%AD%B8%E6%9C%83-%EB%8C%80%EB%A7%8C%EB%8C%80%ED%95%99%EA%B5%90-%ED%95%9C%EA%B5%AD%EC%9C%A0%ED%95%99%EC%83%9D%ED%9A%8C-2125306684192757',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTU Malaysian Student Association (NTUMSA)',
                chinese: '臺大馬來西亞同學會',
                avatar: 'Malaysia',
                image: 'https://i.imgur.com/VZQKUaE.png',
                description: null,
                facebook: 'https://www.facebook.com/%E8%87%BA%E5%A4%A7%E9%A6%AC%E4%BE%86%E8%A5%BF%E4%BA%9E%E5%90%8C%E5%AD%B8%E6%9C%83-128162960609804/',
                instagram: null,
                line: null,
                website: null,
            },
            {
                title: 'NTU Indonesian Students Association (NTUISA)',
                chinese: '國立台灣大學印尼同學會x椰島社',
                avatar: 'Indonesia',
                image: 'https://i.imgur.com/sqStD0y.png',
                description: null,
                facebook: 'https://www.facebook.com/ntuisaofficial/',
                instagram: null,
                line: null,
                website: null,
            },
        ]
    }



]

export {OrganizationsConfigs}